name: Create environment
on:
  workflow_dispatch:

env:
  BBL_IAAS: gcp
  BBL_GCP_REGION: us-east1
  BBL_GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_CREDENTIALS_JSON }}
  ENV_NAME: env-1
  BOSH_DEPLOYMENT: cf
  BOSH_NON_INTERACTIVE: true

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Install Tools
        run: |
          go version

          install_location=/usr/local/bin
          bbl_version=v9.0.35
          bosh_cli_artifact=bosh-cli-7.7.2-linux-amd64
          credhub_cli_artifact=credhub-linux-amd64-2.9.45.tgz
          
          sudo curl https://github.com/cloudfoundry/bosh-bootloader/releases/download/${bbl_version}/bbl-${bbl_version}_linux_amd64 --silent --location --output  $install_location/bbl
          sudo chmod +x $install_location/bbl
          bbl --version
  
          sudo curl https://github.com/cloudfoundry/bosh-cli/releases/download/v7.7.2/$bosh_cli_artifact --silent --output $install_location/bosh --location
          sudo chmod +x $install_location/bosh
          bosh --version
  
          sudo curl https://github.com/cloudfoundry/credhub-cli/releases/download/2.9.45/$credhub_cli_artifact --silent --location --output /tmp/credhub.tgz
          sudo tar -xzf /tmp/credhub.tgz -C $install_location  
          sudo chmod +x $install_location/credhub
          credhub --version

          sudo apt update
          sudo apt install -y build-essential unzip

      - name: Checkout bosh-bootloader
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/bosh-bootloader
          path: bosh-bootloader

      - name: Checkout cli
        uses: actions/checkout@v4
        with:
          path: cli

      - name: Create bbl env
        run: |
          mkdir -p bbl-state && cd bbl-state
          cp -R ${GITHUB_WORKSPACE}/bosh-bootloader/plan-patches/bosh-lite-gcp/* .
          bbl plan --name ${ENV_NAME}
          cp ${GITHUB_WORKSPACE}/cli/.github/bosh-lite-files/bosh-lite-dns.tf terraform/
          cp ${GITHUB_WORKSPACE}/cli/.github/bosh-lite-files/bosh-lite.tfvars vars/
          bbl up

      - id: 'upload-folder'
        name: Upload bbl state to GCS
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'bbl-state'
          destination: 'cf-cli-bosh-lites'

    # Example of using the output
      - id: 'uploaded-files'
        run: |
          echo "files ================= ${{ steps.upload-folder.outputs.uploaded }}"

      - name: Checkout bosh-deployment
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/bosh-deployment
          path: bosh-deployment

      - name: Checkout cf-deployment
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/cf-deployment
          path: cf-deployment
      - name: Checkout bosh bootloader
        uses: actions/checkout@v4
        with:
          repository: cloudfoundry/bosh-bootloader
          path: bosh-bootloader

      - name: Deploy cf
        run: |
          cd bbl-state
          eval "$(bbl print-env)"
          bosh update-runtime-config ${GITHUB_WORKSPACE}/bosh-deployment/runtime-configs/dns.yml --name dns
          STEMCELL_VERSION=$(bosh interpolate ${GITHUB_WORKSPACE}/cf-deployment/cf-deployment.yml --path /stemcells/alias=default/version)
          bosh upload-stemcell "https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-jammy-go_agent?v=${STEMCELL_VERSION}"
          bosh update-cloud-config ${GITHUB_WORKSPACE}/cf-deployment/iaas-support/bosh-lite/cloud-config.yml

          bosh interpolate ${GITHUB_WORKSPACE}/cf-deployment/cf-deployment.yml \
          -o ${GITHUB_WORKSPACE}/cf-deployment/operations/bosh-lite.yml \
          -o ${GITHUB_WORKSPACE}/cf-deployment/operations/enable-v2-api.yml \
          -o ${GITHUB_WORKSPACE}/cf-deployment/operations/use-internal-lookup-for-route-services.yml \
          -o ${GITHUB_WORKSPACE}/cli/.github/ops-files/diego-cell-instances.yml \
          -v system_domain=${SYSTEM_DOMAIN} \
          -v client-secret="${{ secrets.CLIENT_SECRET }}" \
          > ./director.yml

          bosh deploy director.yml

          bosh manifest > manifest.yml

          bosh deploy manifest.yml \          
          -o ${GITHUB_WORKSPACE}/cli/.github/ops-files/add-oidc-provider.yml \
          -o ${GITHUB_WORKSPACE}/cli/.github/ops-files/add-uaa-client-credentials.yml

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3          
