name: "Tests: Integration"

run-name: "Integration [${{ github.event.workflow_run.head_branch }}]: ${{ github.event.workflow_run.head_commit.message }}"

on:
  workflow_call:
    inputs:
      workflow:
        default: all
        type: string
  workflow_dispatch:
    inputs:
      workflow:
        description: Tests to run
        required: true
        type: choice
        options:
          - run-integration-tests-cf-env
          - run-integration-tests-cf-env-with-client-creds

jobs:
  run-integration-tests-cf-env:
    name: Integration tests
    if: ${{ inputs.workflow == 'all' || inputs.workflow == 'run-integration-tests-cf-env' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: false
      os: ubuntu-latest
      name: Integration
    secrets: inherit

  run-integration-tests-cf-env-with-client-creds:
    name: client creds
    if: ${{ inputs.workflow == 'all' || inputs.workflow == 'run-integration-tests-cf-env-with-client-creds' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: true
      os: ubuntu-latest
      name: Integration client creds
    secrets: inherit