name: "Tests: Integration"

run-name: "Integration [${{ github.event.workflow_run.head_branch }}]: ${{ github.event.workflow_run.head_commit.message }}"

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: Tests to run
        required: true
        type: choice
        options:
          - run-integration-tests-cf-env
          - run-integration-tests-cf-env-with-client-creds
          - run-integration-tests-cf-env-with-min-capi
          - run-cats-cf-env
          # - run-integration-windows
          # - run-integration-windows-client-credentials
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed
    branches:
      - v8

jobs:
  # setup:
  #   runs-on: ubuntu-latest 
  #   steps:
  #   - name: Checkout cli
  #     uses: actions/checkout@v4
  #     with:
  #       ref: ${{github.event.workflow_run.head_sha}}  

  run-integration-tests-cf-env:
    # needs: setup
    name: Integration tests
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-integration-tests-cf-env') || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: false
      os: ubuntu-latest
      name: Integration
      is-pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit

  run-integration-tests-cf-env-with-client-creds:
    # needs: setup
    name: client creds
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-integration-tests-cf-env-with-client-creds') || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: true
      os: ubuntu-latest
      name: Integration client creds
      is-pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit

  run-integration-tests-cf-env-with-min-capi:
    # needs: setup
    name: MIN CAPI
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-integration-tests-cf-env-with-min-capi') || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: min
      run-with-client-creds: false
      os: ubuntu-latest
      name: Integration MIN CAPI
      pool-name: cfd_16_11_0
      pool-namespace: tas-devex
      is-pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit

  run-cats-cf-env:
    name: CATS
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-cats-cf-env') || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/tests-integration-reusable.yml
    with:
      capi-version: edge
      run-with-client-creds: false
      os: ubuntu-latest
      name: cats
      is-pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit
  
  #run-integration-windows:
  #  name: Windows
  #  if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-integration-windows') || github.event.workflow_run.conclusion == 'success' }}
  #  uses: ./.github/workflows/tests-integration-reusable.yml
  #  with:
  #    capi-version: edge
  #    run-with-client-creds: false
  #    os: windows-latest
  #    name: Integration windows
  #  secrets: inherit

  #run-integration-windows-client-credentials:
  #  name: Windows with client credentials
  #  if: ${{ (github.event_name == 'workflow_dispatch' && inputs.workflow == 'run-integration-windows-client-credentials') || github.event.workflow_run.conclusion == 'success' }}
  #  uses: ./.github/workflows/tests-integration-reusable.yml
  #  with:
  #    capi-version: edge
  #    run-with-client-creds: true
  #    os: windows-latest
  #    name: Integration windows client credentials
  #  secrets: inherit
