name: "REUSABLE: Integration Tests"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      env-name:
        required: true
        type: string
      gitRef:
        type: string
        default: ${{github.event.workflow_run.head_sha}}

env:
  ENV_NAME: ${{ inputs.env-name }}
  NODES: 16
  FLAKE_ATTEMPTS: ${{ vars.TEST_FLAKE_ATTEMPTS || '4' }}
  BBL_CLI_VERSION: ${{ vars.BBL_CLI_VERSION }}
  BOSH_CLI_VERSION: ${{ vars.BOSH_CLI_VERSION }}
  CREDHUB_CLI_VERSION: ${{ vars.CREDHUB_CLI_VERSION }}

jobs:
  run-integration-tests:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Checkout cli
      uses: actions/checkout@v4
      with:
        ref: ${{inputs.gitRef}}
        fetch-depth: 0
        path: cli

    - name: Checkout cf-acceptance-tests
      if: ${{ inputs.name == 'cats' }}
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-acceptance-tests
        ref: release-candidate
        path: cf-acceptance-tests

    - name: Checkout CF deployment tasks
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/cf-deployment-concourse-tasks
        path: cf-deployment-concourse-tasks

    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: cli/go.mod
        check-latest: true

    - name: Install Tools
      run: |
        go version

        install_location=/usr/local/bin

        sudo curl https://github.com/cloudfoundry/bosh-bootloader/releases/download/v${BBL_CLI_VERSION}/bbl-v${BBL_CLI_VERSION}_linux_amd64 --silent --location --output  $install_location/bbl
        sudo chmod +x $install_location/bbl
        bbl --version

        sudo curl https://github.com/cloudfoundry/bosh-cli/releases/download/v${BOSH_CLI_VERSION}/bosh-cli-${BOSH_CLI_VERSION}-linux-amd64 --silent --output $install_location/bosh --location
        sudo chmod +x $install_location/bosh
        bosh --version

        sudo curl https://github.com/cloudfoundry/credhub-cli/releases/download/${CREDHUB_CLI_VERSION}/credhub-linux-amd64-${CREDHUB_CLI_VERSION}.tgz --silent --location --output /tmp/credhub.tgz
        sudo tar -xzf /tmp/credhub.tgz -C $install_location  
        sudo chmod +x $install_location/credhub
        credhub --version

        sudo apt-get update
        sudo apt-get install -y build-essential unzip

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Download file from GCS
      run: |
        gsutil cp -R gs://cf-cli-bosh-lites/${ENV_NAME} . 
  
    - name: Add CATS config
      if: ${{ inputs.name == 'cats' }}
      run: |
        set -eu

        pushd ./${ENV_NAME}/bbl-state
          eval "$(bbl print-env)"
        popd

        cd cli
        API="api.${ENV_NAME}.app-runtime-interfaces.ci.cloudfoundry.org"

        DOMAIN=$(echo $API | sed "s/^api\.//")
        CF_INT_USERNAME="admin"
        CF_INT_PASSWORD="$(credhub get -n /bosh-${ENV_NAME}/cf/cf_admin_password | bosh interpolate --path /value -)"

        cat << EOF | jq -S . > cats_config.json
        {
          "admin_password": "${CF_INT_PASSWORD}",
          "admin_user": "${CF_INT_USERNAME}",
          "api": "${API}",
          "apps_domain": "${DOMAIN}",
          "backend" : "diego",
          "broker_start_timeout": 330,
          "cf_push_timeout": 210,
          "default_timeout": 120,
          "long_curl_timeout": 210,
          "skip_ssl_validation": true,
          "use_http": true,
          "include_apps": true,
          "include_backend_compatibility": false,
          "include_container_networking": true,
          "include_deployments": true,
          "include_detect": true,
          "include_docker": true,
          "include_cnb": true,
          "include_internet_dependent": true,
          "include_isolation_segments": true,
          "isolation_segment_name": "persistent_isolation_segment",
          "include_private_docker_registry": false,
          "include_route_services": true,
          "include_routing": true,
          "include_routing_isolation_segments": false,
          "include_security_groups": true,
          "include_services": true,
          "include_service_discovery": true,
          "include_service_instance_sharing": true,
          "include_ssh": true,
          "include_sso": false,
          "include_tasks": true,
          "include_tcp_routing": true,
          "include_v3": true,
          "include_zipkin": true
        }
        EOF

        make build
        echo "$PWD/out" >> $GITHUB_PATH
        export PATH="$PWD/out:$PATH"
        cf version

        export CF_USERNAME=${CF_INT_USERNAME}
        export CF_PASSWORD=${CF_INT_PASSWORD}
        cf api ${API} --skip-ssl-validation
        cf auth
        cf enable-feature-flag diego_docker
        cf enable-feature-flag diego_cnb
        cf enable-feature-flag service_instance_sharing

    - name: Run CATS Tests
      if: ${{ inputs.name == 'cats' }}
      run: |
        set -xeu

        export CONFIG
        CONFIG=$(mktemp)

        original_config="${PWD}/cats_config.json"
        cp ${original_config} ${CONFIG}

        cd ./cf-acceptance-tests
        export CF_DIAL_TIMEOUT=11
        export CF_PLUGIN_HOME=$HOME
        go version

        ./bin/test \
          --keep-going \
          --randomize-all \
          --skip-package=helpers \
          --nodes="${NODES}" \
          --flake-attempts=${FLAKE_ATTEMPTS} \
          --timeout="2h" \
          --no-color

    - name: Run Integration Tests
      if: ${{ !inputs.run-with-client-creds  &&  inputs.name != 'cats' }}
      run: |
        pushd ./${ENV_NAME}/bbl-state
          eval "$(bbl print-env)"
        popd

        cd cli
        export CF_INT_PASSWORD="$(credhub get -n /bosh-${ENV_NAME}/cf/cf_admin_password | bosh interpolate --path /value -)"
        export CF_INT_OIDC_USERNAME="admin-oidc"
        export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-${ENV_NAME}/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)
        API_URL="api.${ENV_NAME}.app-runtime-interfaces.ci.cloudfoundry.org"
        export CF_INT_API="https://$API_URL"
        export CF_DIAL_TIMEOUT=15
        export CF_USERNAME=admin
        export GOPATH=$PWD/go
        export PATH="$GOPATH/bin:$PATH"
        export PATH="$PWD/out:$PATH"
        export CF_INT_TEST_NAME="int"
        export CF_PASSWORD=${CF_INT_PASSWORD}


        make build

        cf api ${CF_INT_API} --skip-ssl-validation
        cf auth

        make integration-tests-full-ci

    - name: Run Integration Tests with client credentials
      if: ${{ inputs.run-with-client-creds }}
      env:
        CF_INT_CLIENT_ID: 'potato-face'
        CF_INT_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        pushd ./${ENV_NAME}/bbl-state
          eval "$(bbl print-env)"
        popd

        cd cli
        export CF_INT_PASSWORD="$(credhub get -n /bosh-${ENV_NAME}/cf/cf_admin_password | bosh interpolate --path /value -)"
        export CF_INT_OIDC_USERNAME="admin-oidc"
        export CF_INT_OIDC_PASSWORD=$(credhub get -n /bosh-${ENV_NAME}/cf/uaa_oidc_admin_password | bosh interpolate --path /value -)
        API_URL="api.${ENV_NAME}.app-runtime-interfaces.ci.cloudfoundry.org"
        export CF_INT_API="https://$API_URL"
        export CF_DIAL_TIMEOUT=15
        export CF_USERNAME=admin
        export GOPATH=$PWD/go
        export PATH="$GOPATH/bin:$PATH"
        export PATH="$PWD/out:$PATH"
        export CF_INT_TEST_NAME="cc"
        export CF_PASSWORD=${CF_INT_PASSWORD}

        make build

        cf api ${CF_INT_API} --skip-ssl-validation
        cf auth

        make integration-tests-ci-client-creds

    # - name: Setup tmate session
    #   if: failure()
    #   uses: mxschmitt/action-tmate@v3        