name:     "Test"

permissions:
  contents: write

defaults:
  run:
    shell: bash
    
on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cli
      uses: actions/checkout@v4

    - name: Create draft release
      if: false
      uses: softprops/action-gh-release@v2
      with:
        draft:                   true
        name:                    "DRAFT test"
        tag_name:                "vTest"
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          Makefile
          README.md

    - name: Checkout CLAW
      uses: actions/checkout@v4
      with:
        repository: cloudfoundry/CLAW
        ref: test-release-update
        path: CLAW
        ssh-key: ${{ secrets.GIT_CLI_BOT_SSH_KEY }}

    - name: Add new version to claw variables
      run: |
        set -ex

        pushd CLAW
          pwd > test123.txt
         
          git add test123.txt
          git config user.name cf-cli-eng
          git config user.email cf-cli-eng@pivotal.io
          git commit -m "Add test file"
          git push
        popd
